# GitHub Action for generating a contribution graph with Pac-Man eating your contributions
name: Generate Pac-Man

on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to write the generated svg to the repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Pac-Man Animation
        uses: mifer25/github-contribution-stats-action@v1 # This is the Pac-Man action
        with:
          # Your GitHub username
          user: Uday-04-developer
          # The output file for the animation
          svg_file_name: dist/github-contribution-grid-pacman.svg
          # Optional: you can customize the colors to match your Matrix theme
          # custom_colors: "ff006e,8338ec,3a86ff,F85D7F"
          
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-pacman.svg
          git commit -m "Generate Contribution Pac-Man" || exit 0
          git push
